name: "Terraform Demo"

on:
  workflow_dispatch:
    inputs:
      run_apply:
        description: 'Run terraform apply'
        required: true
        type: boolean
        default: false

jobs:
  terraform:
    name: "Terraform Run"
    runs-on: ubuntu-latest

    env:
      TF_LOG: DEBUG

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v4

      - name: Create .tfvars File
        run: |
          cat <<EOF > terraform.tfvars
          azure_client_id       = "${{ secrets.AZURE_CLIENT_ID }}"
          azure_client_secret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          azure_tenant_id       = "${{ secrets.AZURE_TENANT_ID }}"
          azure_subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          EOF
      
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: ${{ inputs.run_apply == true }}
        run: terraform apply -auto-approve